#!/bin/bash

php $PWD/index.php &
php $PWD/ticker.php &
pid=`echo $!`
sleep 2
while true
do
    if (( $((`date +%s` - `stat -c %Z messages_ids.json`)) > 400 )); then
        kill -9 $pid
        php $PWD/index.php &
        pid=`echo $!`
    fi
    sleep 1
done
